name: Velero Plugin For vSphere CICD Pipeline
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cicd:
    name: Run CICD
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code of velero-plugin-for-vsphere
        uses: actions/checkout@v2
        with:
          path: src/github.com/vmware-tanzu/velero-plugin-for-vsphere
      - name: Download essential GVDDK libraries
        run: |
          cd src/github.com/vmware-tanzu/velero-plugin-for-vsphere && mkdir .libs && cd .libs
          wget --quiet https://gvddk-libs.s3-us-west-1.amazonaws.com/VMware-vix-disklib-7.0.2-17696664.x86_64.tar.gz
          tar xzf VMware-vix-disklib-7.0.2-17696664.x86_64.tar.gz
          chmod 644 $(find vmware-vix-disklib-distrib/lib64/ -type f)
      #- name: Make CI
      #  env:
      #    GOPATH: ${GITHUB_WORKSPACE}
      #  run: |
      #    cd src/github.com/vmware-tanzu/velero-plugin-for-vsphere
      #    make ci
      #- name: Build the plugin and push images to docker hub
      #  if: github.event_name == 'push' && github.repository == 'vmware-tanzu/velero-plugin-for-vsphere'
      #  env:
      #    GOPATH: ${GITHUB_WORKSPACE}
      #  run: |
      #    cd src/github.com/vmware-tanzu/velero-plugin-for-vsphere
      #    echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      #    make push
      # Use the JSON key in secret to login gcr.io
      - uses: 'docker/login-action@v1'
        with:
          registry: 'gcr.io' # or REGION.docker.pkg.dev
          username: '_json_key'
          password: '${{ secrets.GCR_SA_KEY }}'
      # Push image to GCR to facilitate some environments that have rate limitation to docker hub, e.g. vSphere.
      - name: Publish container image to GCR
        if: github.event_name == 'push' && github.repository == 'vmware-tanzu/velero-plugin-for-vsphere'
        env:
          GOPATH: ${GITHUB_WORKSPACE}
        run: |
          cd src/github.com/vmware-tanzu/velero-plugin-for-vsphere
          REGISTRY=gcr.io/velero-gcp make push
